version: '3.4'

services:
  shortly:
    image: shortly
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379

  redis:
    image: redis:latest
