basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: davidsonsatheesh@gmail.com
    name: satheesh ds
  description: This is a sample server celler server.
  title: Swagger Shortner API
  version: "1.0"
paths:
  /shorten:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create a short url for the given url
      operationId: create-short
      parameters:
      - description: url
        in: formData
        name: req_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: new url
          schema:
            type: string
      summary: Create a short url for the given url
  /shorten/topDomains:
    get:
      description: Get top domains shortened
      produces:
      - application/json
      responses: {}
      summary: Get top domains shortened
swagger: "2.0"
